# -*- coding: utf-8 -*-
"""input.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KjqqjEkfBftYmIrLEyv-ONg2Pb_UZmo-
"""

#input file
# The function:"cubic_spline(T,k,skip,T1,T2)" takes T,k,skip,T1,T2 as variable
# where,
# T and k are the arrays with the data points of x-axis and y-axis respectively
# skip is a value such that if user want to perform task based on a subset of the given dataset, put skip=0 or else put skip>=1 to perform on entire given dataset
# for subset, put skip=0
# for entire dataset, put skip=1
# T1 and T2 are the values of T (should be within its given range), for which the user wants to find the interpolation value

from cubic_spline import *

T = np.linspace(50,825,32)
k = np.array([62, 74.7, 79.7, 82, 93.4, 94, 105, 113.82, 139, 135, 138, 130, 148, 160, 161, 170, 175.25, 182.05, 195, 198, 199, 209.37, 220, 227, 229.9, 239, 243.5, 240.33, 243, 269, 270.8, 285])
cubic_spline(T,k,0,60,240)